# permissions for end users to edit clusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterissuer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ejbca-issuer
    app.kubernetes.io/part-of: ejbca-issuer
    app.kubernetes.io/managed-by: kustomize
  name: clusterissuer-editor-role
rules:
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - clusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ejbca-issuer.keyfactor.com
  resources:
  - clusterissuers/status
  verbs:
  - get
